### ISSUE TITLE
Integrate changes needed for migration from myUpway to myUplink

### ISSUE THREAD

**Issue by lobstaj** [Jalle19/pyupway#6]
Kaukora seems to have started to roll out the migration of heat pumps from their myUpway system to the new myUplink (which supposedly is more or less the same as Nibe's Uplink).

It would be good to check what it takes to get pyupway to work with the new system and what parameters can be queried from the new system.

No hurry though, apparently there is plenty of time to switch (a Kaukora rep has mentioned that there is no hurry before summer 2024).

More info:
- https://www.myupway.com/
- myUplink API dev page (yes, they have that :-D ): https://dev.myuplink.com/login

PS: By creating this issue I don't mean to say I expect @Jalle19 to do this, I might be able to contribute too :-)

**Comment by Jalle19** [comment]
@lobstaj interesting, perhaps this means all existing myUplink projects will work with Kaukora units? That would render this project mostly obsolete.

I can give you write access to this repository if you want to contribute more, I don't have access to a system with myUpway anymore anyway.

**Comment by lobstaj** [comment]
Mhh, good point. If there is a good Nibe Uplink python project which allows me to use my existing data easily, then I don't want to put much time into this either.

Let's be in touch on this matter. If I don't find anything which I can easily make work for myself, I don't oppose write access to develop this further.

**Comment by Soiski71** [comment]
Gents, for your awareness a functional code for MYUPLINK has been updated on different project here:
https://github.com/lemanjo/pyupway

**Comment by Jalle19** [comment]
Wondering if perhaps I should archive this repository to avoid confusion? Then people can focus their efforts on the other repository.

**Comment by lobstaj** [comment]
Or maybe add a comment in the project description?

After a quick check I'm not sure the other project has support for inserting values into a db. So it might not totally supersede this project.

I'm not really sure how to continue from here for myself. It's annoying that I apparently can't try the new system without losing access to the old one... This rules out any possibility for a smooth transition. Need to figure out some way which let's me keep my data of the past year.
